### ISSUE TITLE
getAsset Broken for full asset name?

### ISSUE THREAD

**Issue by jonmchan** [grokify/versionone-sdk-ruby#3]
I don't know if it is specific to my version of VersionOne, but I have the strange behavior of querying with the full name as broken. Here is the response when I try using the full name like in the example:

```
client.getAsset("Story","12345") -> returns "<Message>Not Found</Message>" with  error

RuntimeError: E_UNKNOWN_ASSET_NODE_NAME Message
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/versionone_sdk-0.2.0/lib/versionone_sdk/parser_xml_assets.rb:67:in `block in getJsondocForXmlAssetNode'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:187:in `block in each'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `upto'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/nokogiri-1.6.8/lib/nokogiri/xml/node_set.rb:186:in `each'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/versionone_sdk-0.2.0/lib/versionone_sdk/parser_xml_assets.rb:58:in `getJsondocForXmlAssetNode'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/versionone_sdk-0.2.0/lib/versionone_sdk/parser_xml_assets.rb:30:in `getDocForAssetXml'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/versionone_sdk-0.2.0/lib/versionone_sdk/client.rb:81:in `getAssetForTypeAndOid'
    from /home/jchan/.rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/versionone_sdk-0.2.0/lib/versionone_sdk/client.rb:69:in `getAsset'
    from (irb):21
    from bin/console:14:in `<main>'
```

while the following works:

```
client.getAsset("B","12345") # works
client.getAsset("B-12345")  # works
```

**Comment by jonmchan** [comment]
Nevermind, I just did not understand how to properly query by OID. I do think a PR is in order to catch the error message and raise a proper error message. I'll submit a PR for that.

**Comment by grokify** [comment]
@jonmchan Thanks for the update. I was just about to start looking into this. Good idea on the PR.
